name: Dev Pipeline

on:
  push:
    branches:
      - "dev/*"

jobs:
  DeployDev:
    if: github.actor != 'github-actions[bot]'
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      github_environment: DEV
      overlay_path: k8s/overlays/dev
      namespace: halloween-web-app-dev
      deploy_mode: build
      target_tag_prefix: dev
      version_mode: run
      commit_sha: ${{ github.sha }}
      diff_base: ${{ github.event.before }}
    secrets: inherit
