name: Prod Pipeline

on:
  workflow_run:
    workflows: ["Test Pipeline"]
    types:
      - completed

jobs:
  DeployProd:
    name: Promote (if needed) & Deploy Prod
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master'
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      github_environment: PROD
      overlay_path: k8s/overlays/prod
      namespace: halloween-web-app
      deploy_mode: promote
      source_tag_prefix: test
      target_tag_prefix: prod
      commit_sha: ${{ github.event.workflow_run.head_sha }}
    secrets: inherit
